version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - cd ./my-app
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Running tests...
      - CI=true npm run test
     # - npm test

  reports:
    jest_reports:
      files:
        - 'test-report.xml'
      file-format: 'JUNITXML'
      base-directory: my-app