version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - cd ./my-app
      - echo Installing npm packages...
      - npm install
  build:
    commands:
      - echo run tests...
      - npm run test
